config/routes.rb
Konta3::Application.routes.draw do
  namespace :admin do
    resources :users
    resource :profile do
      post 'upload', :on => :collection
    end
    resource :user_session, :only => [ :new, :create, :destroy ]
  end
  resources :password_reset, :only => [ :new, :create, :edit, :update ]
  root :to => 'home#index'
  

end

app/models/admin/user_session.rb
class Admin::UserSession < Authlogic::Session::Base
  # specify configuration here, such as:
  # logout_on_timeout true
  # ...many more options in the documentation
end

app/controllers/admin/user_session_controller.rb
class Admin::UserSessionController < ApplicationController

  def new
    @user_session = Admin::UserSession.new
  end

  def create
    @user_session = Admin::UserSession.new(params[:admin_user_session])
    if params[:commit] == 'Registrarse'
      redirect_to new_admin_profile_url and return
    end
    if @user_session.save
      redirect_to root_url
    else
      render :action => "new"
    end
  end

  def destroy
    current_user_session.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js  #added
    end
  end

end

app/views/admin/user_session/new.html.erb
<%= content_for :new_user_session do %>
	<%= form_for(@user_session, :url => admin_user_session_url) do |f| %>
		<% if @user_session.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@user_session.errors.count, "error") %> prohibited:</h2>
				<ul>
					<% @user_session.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<table>
			<tr>
				<td><%= f.label 'Usuario:' %></td>
				<td><%= f.label 'Contraseña:' %></td>
			</tr>
			<tr>
				<td><%= f.text_field :login %></td>
				<td><%= f.password_field :password %></td>
				<td><%= f.submit "Entrar" %></th>
			</tr>
			<tr>
				<td><%= link_to 'Regístrese', new_admin_profile_path, :title => 'Regístrese como nuevo usuario' %></td>
				<td><%= link_to '¿ Olvidó su contraseña ?', new_password_reset_path,
					:title => 'Registre una nueva contraseña' %></td>
			</tr>
		</table>
	<% end %>
<% end %>