config/routes.rb
Konta3::Application.routes.draw do
  namespace :admin do
    resources :users
    resource :profile do
      post 'upload', :on => :collection
    end
    resource :user_session, :only => [ :new, :create, :destroy ]
  end
  resources :password_reset, :only => [ :new, :create, :edit, :update ]
  root :to => 'home#index'
  

end

app/models/admin/user.rb
class Admin::User < ActiveRecord::Base

  attr_accessible :login, :nombre, :password, :login_fallidos, :failed_login_count, :last_request_at,
    :password_confirmation, :current_login_at, :last_login_at, :email, :current_login_ip, :login_count,
    :last_login_ip, :foto, :foto_file_name, :foto_content_type, :foto_file_size, :foto_updated_at

	acts_as_authentic do |c|
		c.validate_email_field = false
	end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    Notifier.deliver_password_reset_instructions(self).deliver
  end
  
  def login_nombre
		"#{self.login} (#{self.nombre})"
	end

  has_attached_file :foto,
      :default_url => 'user_blank.gif',
      :storage => :s3,
      :s3_credentials => Rails.root.join("config", "s3.yml"),
      :path => "/konta3/fotos_de_usuarios/:id/:basename.:extension"

  validates_attachment_size :foto, :less_than => 1.megabytes,
    :message => "es demasiado grande. Debe pesar menos de 1 mb."

  validates_attachment_content_type :foto,
    :content_type => ['image/png', 'image/jpeg', 'image/gif', 'image/bmp'],
    :message => "debe ser .png, .jpg, .gif o .bmp"

end

app/controllers/admin/users_controller.rb
# -*- encoding : utf-8 -*-
class Admin::UsersController < ApplicationController

	# before_filter :require_user
	# before_filter :es_jorge

	# GET /users
	def index
		@users = params[:format] == 'xls' ? Admin::User.all : (Admin::User.all(:order => 'id DESC'))
		respond_to do |format|
	 		format.html # index.html.erb
			#format.xls
		end
	end
	
	# GET /users/1
	def show
		@user = Admin::User.find(params[:id])
	end
	
	# GET /users/new
	def new
		@user = Admin::User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
	end
	
	# GET /users/1/edit
	def edit
		@user = Admin::User.find(params[:id])
	end
	
	# POST /users
	def create
		@user = Admin::User.new(params[:admin_user])
		if @user.save
			redirect_to(@user)
		else
			render :action => "new"
		end
	end
	
	# PUT /users/1
	def update
		@user = Admin::User.find(params[:id])
		if @user.update_attributes(params[:admin_user])
			redirect_to(@user)
		else
			render :action => "edit"
		end
	end
	
	# DELETE /users/1
	def destroy
		@user = Admin::User.find(params[:id])
		@user.destroy
	  	redirect_to(admin_users_url)
	end

end

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@user.errors.count, "error") %> prohibited:</h2>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<table>
    <tr>
        <th><%= f.label :foto %></th>
        <td>
			<%= image_tag @user.foto, :size => '60x60' %>
			<% if boton != 'Show' %>
				<br /><%= f.file_field :foto %><br/>
			<% end %>
        </td>
    </tr>
	<tr>
		<th><%= f.label :id %></th>
		<td><%= f.text_field :id, :size => 8, :disabled => true %></td>
	</tr>
	<tr>
		<th><%= f.label :login %></th>
		<td><%= f.text_field :login, :disabled => boton == 'Show' %></td>
		<% if controller.controller_name == 'users' %>
			<th><%= f.label :login_fallidos %></th>
			<td><%= f.text_field :failed_login_count, :size => 5, :disabled => true %></td>
		<% end %>
	</tr>
	<tr>
		<th><%= f.label :clave, f.object.new_record? ? nil : 'Cambiar clave' %></th>
		<td><%= f.password_field :password, :disabled => boton == 'Show' %></td>
		<% if controller.controller_name == 'users' %>
			<th><%= f.label :ultima_solicitud %></th>
			<td><%= f.text_field :last_request_at, :size => 30, :disabled => true %></td>
		<% end %>
	</tr>
	<tr>
		<th><%= f.label :confirmacion_de_clave %></th>
		<td><%= f.password_field :password_confirmation, :disabled => boton == 'Show' %></td>
		<% if controller.controller_name == 'users' %>
			<th><%= f.label :actual_login %></th>
			<td><%= f.text_field :current_login_at, :size => 30, :disabled => true %></td>
		<% end %>
	</tr>
	<tr>
		<th><%= f.label :nombre %></th>
		<td><%= f.text_field :nombre, :size => 50, :disabled => boton == 'Show' %></td>
		<% if controller.controller_name == 'users' %>
			<th><%= f.label :ultimo_login %></th>
			<td><%= f.text_field :last_login_at, :size => 30, :disabled => true %></td>
		<% end %>
	</tr>
	<tr>
		<th><%= f.label :email %></th>
		<td><%= f.text_field :email, :size => 50, :disabled => boton == 'Show' %></td>
		<% if controller.controller_name == 'users' %>
			<th><%= f.label :actual_ip %></th>
			<td><%= f.text_field :current_login_ip, :size => 20, :disabled => true %></td>
		<% end %>
	</tr>
	<tr>
		<th><%= f.label :login_oks %></th>
		<td><%= f.text_field :login_count, :size => 5, :disabled => true %></td>
		<% if controller.controller_name == 'users' %>
			<th><%= f.label :ultima_ip %></th>
			<td><%= f.text_field :last_login_ip, :size => 20, :disabled => true %></td>
		<% end %>
	</tr>
</table>

app/views/admin/users/edit.html.erb
<h1><%= 'Editar usuario:' %></h1>
<%= form_for(@user, :html => { :multipart => true }) do |f| %>
	<%= render :partial => 'form', :locals => { :f => f, :boton => 'Actualizar'  } %>
	<p>
		<%= f.submit 'Actualizar' %>
	</p>
<% end %>
<p>
	<%= link_to 'Cancelar', :root %>
</p>

app/views/admin/users/index.html.erb
<h1>Usuarios</h1>
<p>
	<%= link_to 'Nuevo usuario', new_admin_user_path %> |
	<%= link_to 'Exportar a Excel', admin_users_url(:xls) %>
</p>
<table>
	<tr>
		<th>Id</th>
		<th>Usuario</th>
		<th>Nombre</th>
		<th>e-mail</th>
		<th>Ultimo log-in</th>
		<th>Ultima ip</th>
		<th>Links</th>
		<th>Borrar</th>
	</tr>
	<% @users.each do |user| %>
		<tr>
			<td align='right'><%=h user.id %></td>
			<td><%= link_to user.login, edit_admin_user_path(user) %></td>
			<td><%=h user.nombre %></td>
			<td><%=h user.email %></td>
			<td><%=h user.last_login_at %></td>
			<td><%=h user.last_login_ip %></td>
			<td><%#=button_to ' => ', admin_user_links_path(user), :method => :get %></td>
			<td id='link' align='center'>
				<%#=button_to 'X', user, :confirm => 'Esta seguro ?',
					:method => :delete, :disabled => permiso?('B') %>
				<%=button_to 'X', user, :confirm => 'Esta seguro ?', :method => :delete %>
			</td>
		</tr>
	<% end %>
</table>
<p>
	<%= link_to 'Cerrar', :root %>
</p>

app/views/admin/users/new.html.erb
<h1><%= 'Nuevo usuario:' %></h1>
<%= form_for(@user, :html => { :multipart => true }) do |f| %>
	<%= render :partial => 'form', :locals => { :f => f, :boton => 'Crear'  } %>
	<p>
		<%= f.submit 'Crear' %>
	</p>
<% end %>
<p>
	<%= link_to 'Cancelar', admin_users_path %>
</p>

app/views/admin/users/show.html.erb
<h1><%= 'Usuario actualizado:' %></h1>
<%= form_for(@user) do |f| %>
	<%= render :partial => 'form', :locals => { :f => f, :boton => 'Show'  } %>
<% end %>
<p>
	<%= link_to 'Editar', edit_admin_user_path(@user) %>
	<%= link_to 'Nuevo usuario', new_admin_user_path %>
	<%= link_to 'Listar', admin_users_path %>
</p>