config/routes.rb
Konta3::Application.routes.draw do
  namespace :admin do
    resources :users
    resource :profile do
      post 'upload', :on => :collection
    end
    resource :user_session, :only => [ :new, :create, :destroy ]
  end
  resources :password_reset, :only => [ :new, :create, :edit, :update ]
  root :to => 'home#index'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Konta3 <%= controller.action_name %></title>
		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body onload="setFocusDefault()">
			<div id='banner'>
				<div id='logo'>
					<%= link_to "Konta3", root_url, :class => 'titulo', :title => 'Ir a página de inicio' %>
					Plataforma contable en internet.
				</div>
				<div id='login'>
					<% if current_user %>
						<%= link_to image_tag(current_user.foto, :size => '30x30'), edit_admin_profile_path %>
						<%= link_to current_user.login_nombre, edit_admin_profile_path, :class => 'login_nombre' %>
						<%= link_to "Salir", admin_user_session_path, :method => :delete, :class => 'login_nombre' %>
					<% else %>
	  					<%= yield :new_user_session %>
					<% end %>
				</div>
			</div>
			<div id='marco'>
				<div id='menu'>
					<p>
						<%= link_to 'Usuarios', admin_users_path %>
					</p>
				</div>
				<div id='main'>
    				<%= yield %>
				</div>
			</div>
			<div id='pie'>
				(C) 2012 Powered by Jorge Pereyra Software - 
				Todos los derechos reservados - 
				Tucumán - Argentina
			</div>
	</body>
</html>